#
# modified 2021-06-28
#

env:
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  # Spread additional padding evenly around the terminal content.
  padding:
    x: 10
    y: 10
  # Remove buttons
  decorations: none
  # Open in full screen 
  startup_mode: SimpleFullscreen
  # Dimensions if not SimpleFullscreen
  dimensions:
    columns: 140
    lines: 38

# Make background slightly transparent
background_opacity: 0.92

cursor:
  # Block Underline or Beam
  style: Block

font:
  normal:
    # Needs to be powerline font if using zsh theme with powerline
    family: Source Code Pro for Powerline   
  # Font size
  size: 17


# Colors (Hyper)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#ffffff'
  cursor:
    text: '#F81CE5'
    cursor: '#ffffff'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#fe0100'
    green:   '#00a600'
    yellow:  '#feff00'
    blue:    '#0066ff'
    magenta: '#cc00ff'
    cyan:    '#00ffff'
    white:   '#d0d0d0'

  # Bright colors
  bright:
    black:   '#808080'
    red:     '#fe0100'
    green:   '#00d900'
    yellow:  '#feff00'
    blue:    '#0066ff'
    magenta: '#cc00ff'
    cyan:    '#00ffff'
    white:   '#FFFFFF'

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true

# Login shell with arguments
shell:
  program: /bin/zsh
  args:
    - --login

# Startup directory, unset or None for home directory
working_directory: None

scrolling:
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line
  # scrolled when scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
  #
  # To disable this completely, set `faux_multiplier` to 0.
  faux_multiplier: 3

  # Automatically scroll to the bottom when new text is written
  # to the terminal.
  auto_scroll: false

#key_bindings:
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp   }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown }
  - { key: End,      mods: Shift,   action: ScrollToBottom }
  - { key: Home,     mods: Shift,   action: ScrollToTop    }